# Generated by Django 2.1.1 on 2018-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180913_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='logo',
            field=models.ImageField(default='hello', upload_to='teachers/%Y/%m', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
