# Generated by Django 2.1.1 on 2018-09-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_courseorg_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='logo',
            field=models.ImageField(default='', upload_to='teachers/%Y/%m', verbose_name='头像'),
        ),
    ]
