# Generated by Django 2.1.1 on 2018-09-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180913_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='logo',
        ),
        migrations.AddField(
            model_name='teacher',
            name='logo',
            field=models.ImageField(default='', upload_to='teachers/%Y/%m', verbose_name='头像'),
        ),
    ]
